"""initial schema — the baseline, as of S11.

Blocker B12, closed here. Until this file the schema existed wherever somebody had run
`Base.metadata.create_all()`, which is fine for tests and for a laptop and means a deployed
database can never receive a change.

**This is a baseline, not a history.** It creates the schema as it stands at S11 rather than
replaying the eight phases that built it, because there is no deployed database anywhere
whose history it would need to match — reconstructing one would be archaeology performed for
an audience of nobody. The first migration that is a genuine *change* will be the next one.

A database created by `create_all` before this existed is not upgradeable by it: the tables
are already there. `alembic stamp head` is the answer for that case, and it is written down
in docs/DEPLOYMENT.md rather than left to be worked out under pressure.

`assets.purged_at` is the column that made this urgent. It is the retention flag added by
S11 (`app/services/retention.py`), and without a migration path the release that needs it
could not be applied to a database that already existed — which is the abstract problem
turning into a concrete one.

Autogenerated from the models and reviewed, not hand-written. `tests/test_migrations.py`
asserts the two still agree, which is what stops this file going stale the first time
somebody adds a column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca80b70e742'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_assets_id_user')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_user', ['user_id'], unique=False)

    op.create_table('outfits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('occasion', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('degradation_level', sa.Integer(), nullable=False),
    sa.Column('advisory', sa.JSON(), nullable=False),
    sa.Column('vibe', sa.String(length=32), nullable=True),
    sa.Column('fit_preference', sa.String(length=32), nullable=True),
    sa.Column('color_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_outfits_id_user')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index('ix_outfits_user', ['user_id'], unique=False)

    op.create_table('style_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('occasion', sa.String(length=32), nullable=True),
    sa.Column('vibe', sa.String(length=32), nullable=True),
    sa.Column('fit_preference', sa.String(length=32), nullable=True),
    sa.Column('color_preferences', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_style_profiles_id_user')
    )
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_style_profiles_user', ['user_id'], unique=False)

    op.create_table('saved_outfits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('outfit_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id', 'user_id'], ['outfits.id', 'outfits.user_id'], name='fk_saved_outfits_outfit_same_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'outfit_id', name='uq_saved_outfits_user_outfit')
    )
    with op.batch_alter_table('saved_outfits', schema=None) as batch_op:
        batch_op.create_index('ix_saved_outfits_user', ['user_id', 'created_at'], unique=False)

    op.create_table('wardrobe_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('color_primary', sa.String(length=32), nullable=True),
    sa.Column('color_secondary', sa.String(length=32), nullable=True),
    sa.Column('pattern', sa.String(length=32), nullable=True),
    sa.Column('material_guess', sa.String(length=64), nullable=True),
    sa.Column('fit', sa.String(length=32), nullable=True),
    sa.Column('formality', sa.String(length=16), nullable=True),
    sa.Column('season_tags', sa.JSON(), nullable=False),
    sa.Column('occasion_tags', sa.JSON(), nullable=False),
    sa.Column('style_tags', sa.JSON(), nullable=False),
    sa.Column('field_confidence', sa.JSON(), nullable=False),
    sa.Column('corrected_fields', sa.JSON(), nullable=False),
    sa.Column('quality_warnings', sa.JSON(), nullable=False),
    sa.Column('analyzed_by', sa.String(length=128), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_wardrobe_items_id_user')
    )
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.create_index('ix_wardrobe_items_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('ix_wardrobe_items_user_status', ['user_id', 'status'], unique=False)

    op.create_table('item_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wardrobe_item_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('rejected_reason', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_extractions', schema=None) as batch_op:
        batch_op.create_index('ix_item_extractions_item', ['wardrobe_item_id', 'created_at'], unique=False)

    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.String(length=64), nullable=False),
    sa.Column('wardrobe_item_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id', 'user_id'], ['outfits.id', 'outfits.user_id'], name='fk_outfit_items_outfit_same_user'),
    sa.ForeignKeyConstraint(['wardrobe_item_id', 'user_id'], ['wardrobe_items.id', 'wardrobe_items.user_id'], name='fk_outfit_items_item_same_user'),
    sa.PrimaryKeyConstraint('outfit_id', 'wardrobe_item_id')
    )
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.create_index('ix_outfit_items_outfit', ['outfit_id', 'rank'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.drop_index('ix_outfit_items_outfit')

    op.drop_table('outfit_items')
    with op.batch_alter_table('item_extractions', schema=None) as batch_op:
        batch_op.drop_index('ix_item_extractions_item')

    op.drop_table('item_extractions')
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_index('ix_wardrobe_items_user_status')
        batch_op.drop_index('ix_wardrobe_items_user_category')

    op.drop_table('wardrobe_items')
    with op.batch_alter_table('saved_outfits', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_outfits_user')

    op.drop_table('saved_outfits')
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_style_profiles_user')

    op.drop_table('style_profiles')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index('ix_outfits_user')

    op.drop_table('outfits')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_user')

    op.drop_table('assets')
    op.drop_table('users')
    # ### end Alembic commands ###
