"""asset blobs — image bytes in the database, for hosts with no durable disk.

The first migration that is a genuine change rather than a baseline, which is what 0001 said
the next one would be.

`asset_blobs` backs `DatabaseObjectStore` (`app/services/storage.py`). It exists because the
deployment target scales to zero and replaces containers on every release, so a directory
under `STORAGE_ROOT` there is not a weaker place to keep a photograph — it is the wrong
place. The rows in `assets` survive that and the files do not, which shows a user broken
pictures of clothes they own.

Additive and unused by default. `STORAGE_BACKEND` still defaults to `local`, so applying this
changes nothing about a running deployment until that variable is set — which is the safe
order for a zero-downtime rollout: create the table first, point the store at it after.

No foreign key to `assets`, and no `user_id`. Ownership is settled before this table is
reached — signed capability, then the scoped query in `AssetRepository`, and only then is a
storage key handed to the store. A column here would be a second, weaker copy of an
authorisation that has already happened. The retention sweep deletes through the store, so
these rows are removed on exactly the same schedule as the files they replace.

Revision ID: 7bf40a36dafd
Revises: 5ca80b70e742
Create Date: 2026-09-14

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf40a36dafd'
down_revision: Union[str, Sequence[str], None] = '5ca80b70e742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_blobs',
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('storage_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_blobs')
    # ### end Alembic commands ###
