"""jobs — async job records every API instance can read.

The first defect the live deployment found. An upload reached one instance and the poll
after it reached another — a gradual rollout after a configuration change does exactly that —
and job records lived in the memory of the first. The poll answered 404, and the card said
"That item isn't in your wardrobe" for a photograph that was being read correctly.

Additive and unused by default: `JOB_BACKEND` still defaults to `memory`, so applying this
changes nothing about a running deployment until that variable is set. Create the table
first, point the store at it after.

Revision ID: 76a71de999bd
Revises: 7bf40a36dafd
Create Date: 2026-09-14 03:18:18.693895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a71de999bd'
down_revision: Union[str, Sequence[str], None] = '7bf40a36dafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('result_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user')

    op.drop_table('jobs')
    # ### end Alembic commands ###
